---
# Beta! Test before production use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-ui
spec:
  selector:
    matchLabels:
      app: ldap-ui
  template:
    metadata:
      labels:
        app: ldap-ui
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: ldap-ui
        image: dnknth/ldap-ui
        env:
          - name: LDAP_URL
            # Change this value to the service name of your LDAP deployment
            value: "ldap://ldap.cluster.local"
          - name: BASE_DN
            value: "dc=example,dc=org"
          - name: BIND_PATTERN
            # See main README for more info. This sets the main authentication method. 
            value: "cn=%s,dc=example,dc=org"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
